In [1]:
import pandas as pd

spray_df = pd.read_csv('~/Desktop/GA/Week7/project-4/Data/spray.csv')

In [2]:
spray_df.shape

(14835, 4)

In [3]:
spray_df.head(25)

          Date        Time   Latitude  Longitude
0   2011-08-29  6:56:58 PM  42.391623 -88.089163
1   2011-08-29  6:57:08 PM  42.391348 -88.089163
2   2011-08-29  6:57:18 PM  42.391022 -88.089157
3   2011-08-29  6:57:28 PM  42.390637 -88.089158
4   2011-08-29  6:57:38 PM  42.390410 -88.088858
5   2011-08-29  6:57:48 PM  42.390395 -88.088315
6   2011-08-29  6:57:58 PM  42.390673 -88.088002
7   2011-08-29  6:58:08 PM  42.391027 -88.088002
8   2011-08-29  6:58:18 PM  42.391403 -88.088003
9   2011-08-29  6:58:28 PM  42.391718 -88.087995
10  2011-08-29  6:58:38 PM  42.392038 -88.087988
11  2011-08-29  6:58:48 PM  42.392410 -88.088078
12  2011-08-29  6:58:58 PM  42.392800 -88.088332
13  2011-08-29  6:59:08 PM  42.393257 -88.088370
14  2011-08-29  6:59:18 PM  42.393600 -88.088232
15  2011-08-29  7:00:08 PM  42.393203 -88.088417
16  2011-08-29  7:00:18 PM  42.392792 -88.088312
17  2011-08-29  7:00:28 PM  42.392477 -88.088210
18  2011-08-29  7:00:38 PM  42.392385 -88.088697
19  2011-08-29  7:00:48 PM  42.392098 -88.089113
20  2011-08-29  7:00:58 PM  42.392180 -88.089498
21  2011-08-29  7:01:08 PM  42.392428 -88.089790
22  2011-08-29  7:01:18 PM  42.392722 -88.090042
23  2011-08-29  7:01:28 PM  42.392958 -88.090300
24  2011-08-29  7:01:38 PM  42.392990 -88.090895

In [4]:
spray_df['date_lat_long'] = list(zip(spray_df.Date, spray_df.Latitude, spray_df.Longitude))

In [5]:
spray_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14835 entries, 0 to 14834
Data columns (total 5 columns):
Date             14835 non-null object
Time             14251 non-null object
Latitude         14835 non-null float64
Longitude        14835 non-null float64
date_lat_long    14835 non-null object
dtypes: float64(2), object(3)
memory usage: 579.6+ KB

In [6]:
spray_df.shape

(14835, 5)

In [7]:
spray_df.Date.unique()

array(['2011-08-29', '2011-09-07', '2013-07-17', '2013-07-25',
       '2013-08-08', '2013-08-15', '2013-08-16', '2013-08-22',
       '2013-08-29', '2013-09-05'], dtype=object)

In [8]:
### 10 days total of sprays during 2011 and 2013.

# '2011-08-29', --2011
# '2011-09-07', --2011
# '2013-07-17', 
# '2013-07-25',
# '2013-08-08', 
# '2013-08-15', 
# '2013-08-16', 
# '2013-08-22',
# '2013-08-29', 
# '2013-09-05'

In [9]:
spray_df

,Date,Time,Latitude,Longitude,date_lat_long
0,2011-08-29,6:56:58 PM,42.391623,-88.089163,"(2011-08-29, 42.3916233333333, -88.0891633333333)"
1,2011-08-29,6:57:08 PM,42.391348,-88.089163,"(2011-08-29, 42.3913483333333, -88.0891633333333)"
2,2011-08-29,6:57:18 PM,42.391022,-88.089157,"(2011-08-29, 42.3910216666667, -88.0891566666667)"
3,2011-08-29,6:57:28 PM,42.390637,-88.089158,"(2011-08-29, 42.3906366666667, -88.0891583333333)"
4,2011-08-29,6:57:38 PM,42.390410,-88.088858,"(2011-08-29, 42.390409999999996, -88.088858333..."
5,2011-08-29,6:57:48 PM,42.390395,-88.088315,"(2011-08-29, 42.390395, -88.08831500000001)"
6,2011-08-29,6:57:58 PM,42.390673,-88.088002,"(2011-08-29, 42.3906733333333, -88.0880016666667)"
7,2011-08-29,6:58:08 PM,42.391027,-88.088002,"(2011-08-29, 42.391026666666704, -88.088001666..."
8,2011-08-29,6:58:18 PM,42.391403,-88.088003,"(2011-08-29, 42.391403333333294, -88.088003333..."
9,2011-08-29,6:58:28 PM,42.391718,-88.087995,"(2011-08-29, 42.391718333333294, -88.087994999..."
10,2011-08-29,6:58:38 PM,42.392038,-88.087988,"(2011-08-29, 42.392038333333296, -88.087988333..."
11,2011-08-29,6:58:48 PM,42.392410,-88.088078,"(2011-08-29, 42.39241, -88.0880783333333)"
12,2011-08-29,6:58:58 PM,42.392800,-88.088332,"(2011-08-29, 42.3928, -88.0883316666667)"
13,2011-08-29,6:59:08 PM,42.393257,-88.088370,"(2011-08-29, 42.3932566666667, -88.08837)"
14,2011-08-29,6:59:18 PM,42.393600,-88.088232,"(2011-08-29, 42.3936, -88.0882316666667)"
15,2011-08-29,7:00:08 PM,42.393203,-88.088417,"(2011-08-29, 42.3932033333333, -88.0884166666667)"
16,2011-08-29,7:00:18 PM,42.392792,-88.088312,"(2011-08-29, 42.3927916666667, -88.0883116666667)"
17,2011-08-29,7:00:28 PM,42.392477,-88.088210,"(2011-08-29, 42.3924766666667, -88.08821)"
18,2011-08-29,7:00:38 PM,42.392385,-88.088697,"(2011-08-29, 42.392385, -88.08869666666669)"
19,2011-08-29,7:00:48 PM,42.392098,-88.089113,"(2011-08-29, 42.392098333333294, -88.089113333..."
20,2011-08-29,7:00:58 PM,42.392180,-88.089498,"(2011-08-29, 42.392179999999996, -88.089498333..."
21,2011-08-29,7:01:08 PM,42.392428,-88.089790,"(2011-08-29, 42.3924283333333, -88.08979000000..."
22,2011-08-29,7:01:18 PM,42.392722,-88.090042,"(2011-08-29, 42.3927216666667, -88.09004166666..."
23,2011-08-29,7:01:28 PM,42.392958,-88.090300,"(2011-08-29, 42.3929583333333, -88.0903)"
24,2011-08-29,7:01:38 PM,42.392990,-88.090895,"(2011-08-29, 42.392990000000005, -88.090894999..."
25,2011-08-29,7:01:48 PM,42.393002,-88.091612,"(2011-08-29, 42.393001666666706, -88.091611666..."
26,2011-08-29,7:01:58 PM,42.393008,-88.092010,"(2011-08-29, 42.3930083333333, -88.09201)"
27,2011-08-29,7:02:08 PM,42.393020,-88.092548,"(2011-08-29, 42.39302, -88.0925483333333)"
28,2011-08-29,7:02:18 PM,42.393103,-88.093182,"(2011-08-29, 42.39310333333329, -88.0931816666..."
29,2011-08-29,7:02:28 PM,42.393118,-88.093737,"(2011-08-29, 42.3931183333333, -88.0937366666667)"
...,...,...,...,...,...
14805,2013-09-05,8:28:41 PM,42.009215,-87.815097,"(2013-09-05, 42.009215000000005, -87.815096666..."
14806,2013-09-05,8:28:51 PM,42.008713,-87.815108,"(2013-09-05, 42.0087133333333, -87.8151083333333)"
14807,2013-09-05,8:29:01 PM,42.008163,-87.815073,"(2013-09-05, 42.0081633333333, -87.8150733333333)"
14808,2013-09-05,8:29:11 PM,42.007722,-87.815087,"(2013-09-05, 42.007721666666704, -87.815086666..."
14809,2013-09-05,8:29:21 PM,42.007200,-87.815078,"(2013-09-05, 42.0072, -87.8150783333333)"
14810,2013-09-05,8:29:31 PM,42.006698,-87.815073,"(2013-09-05, 42.0066983333333, -87.8150733333333)"
14811,2013-09-05,8:29:41 PM,42.006262,-87.815047,"(2013-09-05, 42.0062616666667, -87.8150466666667)"
14812,2013-09-05,8:29:51 PM,42.006235,-87.814400,"(2013-09-05, 42.006235, -87.8144)"
14813,2013-09-05,8:30:01 PM,42.006277,-87.813815,"(2013-09-05, 42.0062766666667, -87.813815)"
14814,2013-09-05,8:30:11 PM,42.006818,-87.813775,"(2013-09-05, 42.0068183333333, -87.813775)"
14815,2013-09-05,8:30:21 PM,42.007355,-87.813768,"(2013-09-05, 42.007355, -87.8137683333333)"
14816,2013-09-05,8:30:31 PM,42.007818,-87.813775,"(2013-09-05, 42.0078183333333, -87.813775)"
14817,2013-09-05,8:30:41 PM,42.008387,-87.813745,"(2013-09-05, 42.0083866666667, -87.813745)"
14818,2013-09-05,8:30:51 PM,42.008933,-87.813720,"(2013-09-05, 42.008933333333296, -87.813719999..."
14819,2013-09-05,8:31:01 PM,42.009487,-87.813683,"(2013-09-05, 42.0094866666667, -87.8136833333333)"
14820,2013-09-05,8:31:11 PM,42.010087,-87.813695,"(2013-09-05, 42.0100866666667, -87.813695)"
14821,2013-09-05,8:31:21 PM,42.010682,-87.813713,"(2013-09-05, 42.010681666666706, -87.813713333..."
14822,2013-09-05,8:31:31 PM,42.011213,-87.813688,"(2013-09-05, 42.011213333333295, -87.813688333..."
14823,2013-09-05,8:31:51 PM,42.011340,-87.812347,"(2013-09-05, 42.011340000000004, -87.812346666..."
14824,2013-09-05,8:33:11 PM,42.010135,-87.812330,"(2013-09-05, 42.010135, -87.81233)"
14825,2013-09-05,8:33:21 PM,42.009693,-87.812338,"(2013-09-05, 42.009693333333296, -87.812338333..."
14826,2013-09-05,8:33:31 PM,42.009125,-87.812338,"(2013-09-05, 42.009125, -87.8123383333333)"
14827,2013-09-05,8:33:41 PM,42.008507,-87.812357,"(2013-09-05, 42.008506666666705, -87.812356666..."
14828,2013-09-05,8:33:51 PM,42.007897,-87.812335,"(2013-09-05, 42.0078966666667, -87.812335)"
14829,2013-09-05,8:34:01 PM,42.007218,-87.812338,"(2013-09-05, 42.0072183333333, -87.8123383333333)"
14830,2013-09-05,8:34:11 PM,42.006587,-87.812355,"(2013-09-05, 42.006586666666706, -87.812355000..."
14831,2013-09-05,8:35:01 PM,42.006192,-87.816015,"(2013-09-05, 42.0061916666667, -87.81601500000..."
14832,2013-09-05,8:35:21 PM,42.006022,-87.817392,"(2013-09-05, 42.006021666666705, -87.817391666..."
14833,2013-09-05,8:35:31 PM,42.005453,-87.817423,"(2013-09-05, 42.0054533333333, -87.8174233333333)"
14834,2013-09-05,8:35:41 PM,42.004805,-87.817460,"(2013-09-05, 42.004805, -87.81746)"

In [11]:
spray_df.date_lat_long.groupby(spray_df.Date).value_counts()

Date        date_lat_long
2011-08-29  (2011-08-29, 42.38946, -88.09389499999999)             1
            (2011-08-29, 42.389711666666706, -88.09391)            1
            (2011-08-29, 42.3897216666667, -88.09383333333331)     1
            (2011-08-29, 42.389835, -88.0942183333333)             1
            (2011-08-29, 42.389843333333296, -88.0946666666667)    1
            (2011-08-29, 42.389855, -88.09508000000001)            1
            (2011-08-29, 42.3898566666667, -88.09490500000001)     1
            (2011-08-29, 42.389858333333294, -88.0954866666667)    1
            (2011-08-29, 42.389866666666705, -88.0958783333333)    1
            (2011-08-29, 42.38987, -88.0962583333333)              1
            (2011-08-29, 42.3900483333333, -88.096435)             1
            (2011-08-29, 42.390066666666705, -88.095155)           1
            (2011-08-29, 42.390335, -88.0964433333333)             1
            (2011-08-29, 42.390395, -88.08831500000001)            1
            (2011-08-29, 42.390409999999996, -88.0888583333333)    1
            (2011-08-29, 42.390570000000004, -88.0951433333333)    1
            (2011-08-29, 42.3906366666667, -88.0891583333333)      1
            (2011-08-29, 42.3906416666667, -88.09644)              1
            (2011-08-29, 42.3906733333333, -88.0880016666667)      1
            (2011-08-29, 42.3909516666667, -88.0964366666667)      1
            (2011-08-29, 42.3909533333333, -88.095145)             1
            (2011-08-29, 42.3910216666667, -88.0891566666667)      1
            (2011-08-29, 42.391026666666704, -88.0880016666667)    1
            (2011-08-29, 42.391225, -88.0951533333333)             1
            (2011-08-29, 42.3912383333333, -88.0964683333333)      1
            (2011-08-29, 42.39127, -88.096035)                     1
            (2011-08-29, 42.391275, -88.0956083333333)             1
            (2011-08-29, 42.391296666666705, -88.0952033333333)    1
            (2011-08-29, 42.3913483333333, -88.0891633333333)      1
            (2011-08-29, 42.391403333333294, -88.0880033333333)    1
                                                                  ..
2013-09-05  (2013-09-05, 42.0182933333333, -87.8176416666667)      1
            (2013-09-05, 42.0184, -87.816435)                      1
            (2013-09-05, 42.01858, -87.8139516666667)              1
            (2013-09-05, 42.0186, -87.8205466666667)               1
            (2013-09-05, 42.0186283333333, -87.809055)             1
            (2013-09-05, 42.0186366666667, -87.818975)             1
            (2013-09-05, 42.018646666666704, -87.8198433333333)    1
            (2013-09-05, 42.0186566666667, -87.818635)             1
            (2013-09-05, 42.01866333333329, -87.8174833333333)     1
            (2013-09-05, 42.018666666666704, -87.8114833333333)    1
            (2013-09-05, 42.018671666666705, -87.8176666666667)    1
            (2013-09-05, 42.0186816666667, -87.815155)             1
            (2013-09-05, 42.018685, -87.8075416666667)             1
            (2013-09-05, 42.01869, -87.81674833333331)             1
            (2013-09-05, 42.0187, -87.81269499999999)              1
            (2013-09-05, 42.0187016666667, -87.8168116666667)      1
            (2013-09-05, 42.018711666666704, -87.8160316666667)    1
            (2013-09-05, 42.018733333333294, -87.807815)           1
            (2013-09-05, 42.018735, -87.8102533333333)             1
            (2013-09-05, 42.018736666666705, -87.8150666666667)    1
            (2013-09-05, 42.018753333333294, -87.8144266666667)    1
            (2013-09-05, 42.018765, -87.8141716666667)             1
            (2013-09-05, 42.018781666666705, -87.8132433333333)    1
            (2013-09-05, 42.018805, -87.8120183333333)             1
            (2013-09-05, 42.0188133333333, -87.8122083333333)      1
            (2013-09-05, 42.01882, -87.80949333333331)             1
            (2013-09-05, 42.018840000000004, -87.8112283333333)    1
            (2013-09-05, 42.018865000000005, -87.8103383333333)    1
            (2013-09-05, 42.0188833333333, -87.80939000000001)     1
            (2013-09-05, 42.0189066666667, -87.8086233333333)      1
Name: date_lat_long, Length: 14294, dtype: int64